// ACCOUNTS
export const ADD_ACCOUNT = 'ADD_ACCOUNT'
export const FETCH_ACCOUNT = 'ADD_ACCOUNT'
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'

// TRANSACTIONS
export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS'
export const ADD_TRANSACTION = 'ADD_TRANSACTION'